apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraoq-backend
  namespace: kraoq
  labels:
    app: kraoq-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kraoq-backend
  template:
    metadata:
      labels:
        app: kraoq-backend
    spec:
      containers:
      - name: kraoq-backend
        image: ghcr.io/kraoq/kraoq-backend:sha-e1df8ea83c1efb48c609e46dbf86163b475fef89
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: AUDIO_PROCESSOR_URL
          value: "http://10.0.0.X:3002" # REPLACE with your WireGuard Client IP
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: kraoq-secrets
              key: mongo-root-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kraoq-secrets
              key: mongo-root-password
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kraoq-secrets
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kraoq-secrets
              key: google-client-secret
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: kraoq-secrets
              key: session-secret
        - name: AUDIO_PROCESSOR_API_KEY
          valueFrom:
            secretKeyRef:
              name: kraoq-secrets
              key: audio-processor-api-key
        volumeMounts:
        - name: data-volume
          mountPath: /app/uploads
          subPath: uploads
        - name: data-volume
          mountPath: /app/cache.json
          subPath: cache.json
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: kraoq-backend-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kraoq-backend-service
  namespace: kraoq
spec:
  selector:
    app: kraoq-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
