apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kraoq-mongo-pvc
  namespace: kraoq
  labels:
    app: kraoq-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
