apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kraoq-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/KraoQ.git
    targetRevision: main
    path: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: kraoq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kraoq-mongo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/KraoQ.git
    targetRevision: main
    path: database
  destination:
    server: https://kubernetes.default.svc
    namespace: kraoq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
